name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        cd server
        IMAGE_NAME=pcstat:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Push the Docker image
      run: |
        IMAGE_NAME=my-image-name:$(date +%s)
        docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
